#!/bin/sh
# before running this script, you have to place some files as follows: 
# ${KEYSTORE} - key generated by `keytool -genkey`
# ${READER_DIR}/<name>/<name>_%03d_{1,2}.ogg - audio file
# ${READER_DIR}/<name>-licence - copyright and licence of audio file

ROOT="$(git rev-parse --show-toplevel)"
KEYSTORE="${ROOT}/keystore/hpnpwd.keystore"
READER_DIR="${ROOT}/players/"
READER_ASSETS="${ROOT}/src/main/assets/reader"
TARGET_BASE="${ROOT}"

function die(){
  echo "$@"
  exit
}

if [ $# -eq 0 ];then
  echo "USAGE: $0 [reader]"
  exit
fi
if [ ! -d "${READER_DIR}/$1" ];then
  echo directory "${READER_DIR}/$1" not found
  exit
fi

for f in "${READER_ASSETS}"/*; do
  if [ -h "${f}" ];then
    unlink "${f}"
  fi
done
ln -s "${READER_DIR}"/$1 "${READER_ASSETS}"
cd ${ROOT}

# sbt release generates jarsigned and zipaligned apk
sbt aarlib-dependencies release || die compile FAILED

APK_FILE=$(ls ${ROOT}/target/wasuramoti-signed-*.apk)
if [ $? -ne 0 ];then
  exit
fi
READER=$(unzip -t ${APK_FILE} | grep -o -m 1 'testing: assets/reader/[^/]*/' | sed -re 's!.*/([^/]*)/$!\1!')

AUDIO_LICENCE=${READER_DIR}/${READER}-licence

if [ ! "${READER}" ];then
  echo no assets/reader found in ${APK_FILE}
  exit
fi

VERSION=$(echo "${APK_FILE}" | sed -re 's!.*/wasuramoti-signed-(.*).apk!\1!')
TARGET_DIR="${TARGET_BASE}/wasuramoti-android-${READER}-${VERSION}"
if [ -e "${TARGET_DIR}" ];then
  rm -rf "${TARGET_DIR}"
fi
mkdir "${TARGET_DIR}"

TARGET_FILE="${TARGET_DIR}/wasuramoti-${READER}-${VERSION}.apk"

cp -f "${APK_FILE}" "${TARGET_FILE}"
echo "copied to ${TARGET_FILE}"

cat "${ROOT}/README" | sed -e "/__WRITE_AUDIO_LICENCE_HERE__/{
r ${AUDIO_LICENCE}
d
}" > "${TARGET_DIR}/README"
cp "${ROOT}/COPYING" "${TARGET_DIR}"
cp "${ROOT}/src/main/jni/libvorbis-"*"/COPYING" "${TARGET_DIR}/COPYING-OGGVORBIS"
